/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.directorio_amigos;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;

import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class Ventana_principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_principal.class.getName());

    /**
     * Creates new form Ventana_principal
     */
    public Ventana_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_nombre = new javax.swing.JLabel();
        label_numero = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        campo_numero = new javax.swing.JTextField();
        boton_crear = new javax.swing.JButton();
        boton_leer = new javax.swing.JButton();
        boton_actualizar = new javax.swing.JButton();
        boton_borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_mensajes = new javax.swing.JTextArea();
        boton_limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nombre.setText("Nombre");

        label_numero.setText("Número");

        boton_crear.setText("Crear");
        boton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearActionPerformed(evt);
            }
        });

        boton_leer.setText("Leer");

        boton_actualizar.setText("Actualizar");

        boton_borrar.setText("Borrar");

        area_mensajes.setColumns(20);
        area_mensajes.setRows(5);
        jScrollPane1.setViewportView(area_mensajes);

        boton_limpiar.setText("Limpiar mensajes");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("Historial de acciones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nombre)
                            .addComponent(label_numero))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campo_nombre)
                            .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(boton_limpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton_crear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_leer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_actualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton_borrar))
                            .addComponent(jLabel1))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nombre)
                    .addComponent(campo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numero)
                    .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_crear)
                    .addComponent(boton_leer)
                    .addComponent(boton_actualizar)
                    .addComponent(boton_borrar))
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_limpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearActionPerformed
        // TODO add your handling code here:
        /* accion realizada cuando se pulsa el boton crear */

        try {
            String nombre_igresado = campo_nombre.getText(); // se obtiene el nombre ingresado en el campo de texto
            long numero_ingresado = Long.parseLong(campo_numero.getText()); // se obiene el numero ingresado en el campo de texto correspondiente y se convierta a long
            String numero_string = campo_numero.getText();
            String nombre;
            long numero;
            int indice;
            boolean encontrado = false;
            String linea;


            File archivo = new File("entrega_5/directorio_amigos/src/main/java/com/mycompany/directorio_amigos/files/archivo_directorio.txt"); // se crea un objeto File con la ruta del archivo
            if (archivo.exists() == false){
                /* si el archivo no existe, entonces lo crea */
                archivo.createNewFile();
            }
            RandomAccessFile raf = new RandomAccessFile(archivo, "rw");

            /* se recorre el archivo para verificar si el nuevo nombre existe o no existe */
            while (raf.getFilePointer() < raf.length()) {
                linea = raf.readLine(); // se lee una linea del archivo
                String [] registro = linea.split("!"); // see separa la linea en nombre y numero con el caracter clave '!'

                nombre = registro[0]; // se obtiene el nombre del registro actual 
                numero = Long.parseLong(registro[1]); // se obriene el numero del registro actual

                if (nombre.equals(nombre_igresado) || numero == numero_ingresado){
                    encontrado = true;
                    JOptionPane.showMessageDialog(null, "El nombre o el número ya existen en el directorio."); // se muestra un mensaje de error
                    raf.close(); // se cierra el archivo
                    area_mensajes.append("\nEl nombre o el número ya existen, por favor modifique la entrada.\n"); // se pide al usuario modificar la entrada
                    break;
                }
                
            }
            if (encontrado == false){
                raf.writeBytes(nombre_igresado + "!" + numero_string); // se escribe el nuevo registro en el archivo
                raf.writeBytes(System.lineSeparator()); // se escribe un salto de linea
                JOptionPane.showMessageDialog(null, "Amigo agregado al directorio correctamente."); // se muestra un mensaje de confirmacion
                raf.close(); // se cierra el archivo
                campo_nombre.setText(""); // se limpia el campo de texto del nombre
                campo_numero.setText(""); // se limpia el campo de texto del numero
                area_mensajes.append("\nAmigo agregado al directorio correctamente.\n"); // se muestra el mensaje en el area de mensajes
                area_mensajes.append("Nombre: " + nombre_igresado + ", Número: " + numero_string + "\n"); // se muestra el contacto agregado
            }



        }catch (IOException ioe){
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error abriendo o creando el archivo.");
        }


        
        
    }//GEN-LAST:event_boton_crearActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        // TODO add your handling code here:
        area_mensajes.setText("");        
        
        
    }//GEN-LAST:event_boton_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area_mensajes;
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_crear;
    private javax.swing.JButton boton_leer;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_numero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_numero;
    // End of variables declaration//GEN-END:variables
}
