/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio_412;

/**
 *
 * @author daniel
 */
public class Ventana_principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_principal.class.getName());

    /**
     * Creates new form Ventana_principal
     */
    public Ventana_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_numero = new javax.swing.JLabel();
        label_logaritmoNatural = new javax.swing.JLabel();
        label_raizCuadrada = new javax.swing.JLabel();
        campo_numero = new javax.swing.JTextField();
        campo_logaritmoNatural = new javax.swing.JTextField();
        campo_raizCuadrada = new javax.swing.JTextField();
        boton_calcular = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        label_mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_numero.setText("Número");

        label_logaritmoNatural.setText("Logaritmo natural");

        label_raizCuadrada.setText("Raíz cuadrada");

        boton_calcular.setText("Calcular");
        boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_calcularActionPerformed(evt);
            }
        });

        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });

        label_mensaje.setText("El número debe ser mayor que cero.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_mensaje)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_logaritmoNatural)
                            .addComponent(label_raizCuadrada)
                            .addComponent(boton_calcular)
                            .addComponent(label_numero))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(boton_limpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campo_logaritmoNatural, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(campo_raizCuadrada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campo_numero))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_numero)
                    .addComponent(campo_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_logaritmoNatural)
                    .addComponent(campo_logaritmoNatural, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_raizCuadrada)
                    .addComponent(campo_raizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_calcular)
                    .addComponent(boton_limpiar))
                .addGap(29, 29, 29)
                .addComponent(label_mensaje)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_calcularActionPerformed
        // TODO add your handling code here:

        /* el boton calcular obtiene el numero de la casilla numero,
        realiza los calculos y muestra los resultados en las casillas correspondientes */
        
        double numero, logaritmo_natural, raiz_cuadrada;
        numero = Double.parseDouble(campo_numero.getText());
        
        if (numero > 0){
            logaritmo_natural = Calculos_numericos.calcular_logaritmoNatural(numero);
            raiz_cuadrada = Calculos_numericos.calcular_raizCuadrada(numero);
            campo_logaritmoNatural.setText(String.valueOf(logaritmo_natural));
            campo_raizCuadrada.setText(String.valueOf(raiz_cuadrada));
            
        } else {
            label_mensaje.setText("El número debe ser mayor que cero.");
            campo_logaritmoNatural.setText("");
            campo_raizCuadrada.setText("");
        }
  


    }//GEN-LAST:event_boton_calcularActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        // TODO add your handling code here:
        /* el boton numero limpia todas las casillas */
        campo_numero.setText("");
        campo_logaritmoNatural.setText("");
        campo_raizCuadrada.setText("");       
        
    }//GEN-LAST:event_boton_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_calcular;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JTextField campo_logaritmoNatural;
    private javax.swing.JTextField campo_numero;
    private javax.swing.JTextField campo_raizCuadrada;
    private javax.swing.JLabel label_logaritmoNatural;
    private javax.swing.JLabel label_mensaje;
    private javax.swing.JLabel label_numero;
    private javax.swing.JLabel label_raizCuadrada;
    // End of variables declaration//GEN-END:variables
}
